// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "trial1.h"

Fl_Double_Window* CFluidWindow::CFluidFunction() {
  { win_app = new Fl_Double_Window(635, 445, "image_window");
    win_app->user_data((void*)(this));
    { box_jpeg = new Fl_Box(130, 26, 385, 303, "label");
    } // Fl_Box* box_jpeg
    { button_click = new Fl_Button(240, 370, 170, 25, "Click to show image");
    } // Fl_Button* button_click
    win_app->end();
  } // Fl_Double_Window* win_app
  return win_app;
}
