// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef trial1_h
#define trial1_h
#include <FL/Fl.H>
#include <iostream>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

class CFluidWindow {
public:
  Fl_Double_Window* CFluidFunction();
  Fl_Double_Window *win_app;
  Fl_Box *box_jpeg;
  Fl_Button *button_click;
};
#endif
